name: DailyUpdate
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python script.py
      - run: |
          git config user.name "AutoBot"
          git config user.email "bot@github.com"
          git add data.json
          git commit -m "Daily Content Update" || exit 0
          git push
